### ISSUE TITLE
Background color for the placeholder still appears 

### ISSUE THREAD

**Issue by ttsik** [jobandtalent/AnimatedTextInput#12] opened 2016-09-09 09:06 UTC
Although everything is nice about this control. the background color in the placeholder does not go away. I understand that author published a version that removes it, but I was not able to get the update with pod

Thanks a lot in advance

**Comment by victorBaro** [comment] 2016-09-09 16:11
Hello @tssik, 

Can you please explain what does mean? I don't understand the question. "_the background color in the placeholder does not go away_".

Maybe you can upload a screenshot?

**Comment by ttsik** [comment] 2016-09-13 14:57
Hi, first of all let me apologize for the late reply and also congratulate you for the great control. It is very handy actually and well built. 

Referring to the screenshot, I have two AnimatedTextInput controls but the background color of the placeholder is red and I was not able to get rid of it. 

I am using version 0.30 (also tried 0.31)

From the publishing history, I saw that you have the following comment "Remove placeholder layer background color" which I assume that is related to the issue I am facing. 

I would really appreciate the help

Waiting for your answer
Thanks

![simulator screen shot sep 13 2016 4 50 30 pm](https://cloud.githubusercontent.com/assets/17131453/18478712/847712a4-79d2-11e6-80e7-2336e93e9b9d.png)

**Comment by victorBaro** [comment] 2016-09-13 15:09
Hello @ttsik 
Yes, by mistake I pushed a version with a red background color in version 0.3.0. 
Please update the pod to version 0.3.2, it should be fixed. Let me know if the problem is still happening.

And thank you for your comments.

I am closing the issue, but feel free to reopen in case you try 0.3.2 and still happens.

**Closed as completed by victorBaro** 2016-09-13 15:09 UTC
